blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    #  path('', views.IndexView.as_view()),

    path('detail/<int:pk>/', views.detail_page, name='detail'),
    path('', views.home_page,name='home'),
    path('about-us/', views.about_us_page, name='about-us'),
    path('what-drives-us/', views.about_us_page_two, name='what-drives-us'),
    path('our-advertising-partners/', views.about_us_page_three, name='our-advertising-partners'),
    path('make-money-with-us/', views.about_us_page_four, name='make-money-with-us'),
    path('write-for-us/', views.write_for_us_page, name='write-for-us'),
    path('send-us-your-pr/', views.send_us_your_pr_page, name='send-us-your-pr'),
    path('advertise/', views.advertise_page, name='advertise'),
    path('temp/', views.write_for_us_page, name='temp'),
    path('contact-us',view=views.contact_us, name='contact-us'),
    path('article-page/<int:menu_id>/',view=views.article_page, name='article-page')
]

themisource/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include('blog.urls')),
  path('summernote/', include('django_summernote.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import datetime
from django.contrib.auth.models import User
from django.core import validators
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy as _


def post_upload_to(instance, filename):
    return 'blog/post/{filename}'.format(filename=filename)


def logo_upload_to(instance, filename):
    return 'blog/post/{filename}'.format(filename=filename)


def ns_upload_to(instance, filename):
    return 'blog/source/{filename}'.format(filename=filename)


def wfu_upload_to(instance, filename):
    return 'blog/write4us/{filename}'.format(filename=filename)


def press_upload_to(instance, filename):
    return 'blog/press/{filename}'.format(filename=filename)


class Category(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Post(models.Model):

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    editor = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='editor')
    post_date = models.DateTimeField(auto_now_add=True)
    schedule_time = models.DateTimeField(default=timezone.now)
    post_content = models.TextField()
    post_title = models.CharField(max_length=1000, null=False)
    post_status = models.CharField(max_length=20,  choices=options, default='published')
    post_modified = models.DateTimeField(auto_now=True, null=True)
    category = models.ForeignKey(Category, related_name='category_id', on_delete=models.CASCADE)
    city = models.CharField(max_length=100, null=True, blank=True)
    tags = models.CharField(max_length=500, null=True, blank=True)
    keywords = models.CharField(max_length=500, null=True, blank=True)
    slug = models.SlugField(max_length=200)
    meta_title = models.CharField(max_length=500, null=True, blank=True)
    meta_description = models.TextField(null=True, blank=True)
    feature_image_url = models.ImageField(_("Image"), upload_to=post_upload_to, default='blog/post/default.jpg')
    seen = models.BigIntegerField(default=0)
    objects = models.Manager()  # default manager

    class Meta:
        ordering = ('-post_date',)

    def __str__(self):
        return self.post_title

    def published(self):
        return self.schedule_time < timezone.now() and self.post_status == 'published'


class Comments(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user_name = models.CharField(max_length=250)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user_name


class PressRelease(models.Model):
    company_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, validators=[validators.EmailValidator])
    image = models.ImageField(_("Image"), upload_to=press_upload_to, default='blog/press/default.jpg')
    heading = models.CharField(max_length=500)
    description = models.TextField()
    created_at = models.DateTimeField(default=timezone.now, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.heading


class WriteForUs(models.Model):
    company_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, validators=[validators.EmailValidator])
    image = models.ImageField(_("Image"), upload_to=wfu_upload_to, default='blog/write4us/default.jpg')
    heading = models.CharField(max_length=500)
    description = models.TextField()
    created_at = models.DateTimeField(default=timezone.now, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.heading


class NewsSource(models.Model):
    title = models.CharField(max_length=500)
    description = models.TextField()
    url = models.URLField()
    image = models.ImageField(_("Image"), upload_to=ns_upload_to, default='blog/source/default.png')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.title


class Menu(models.Model):
    title = models.CharField(max_length=100, unique=True)
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE, related_name='children')
    url = models.URLField(blank=True, null=True)
    is_static = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name='menus')
    title = models.CharField(max_length=255)
    body = models.TextField()
    slug = models.SlugField(null=False, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

blog/forms.py
from django import forms
from django.core import validators
from .models import *


class PRForm(forms.Form):
    company_name = forms.CharField(label='COMPANY NAME', max_length=100, required=True)
    email = forms.EmailField(label='EMAIL ADDRESS', max_length=100, validators=[validators.EmailValidator],
                             required=True)
    image = forms.ImageField(label='PRESS RELEASE IMAGE', widget=forms.ImageField, required=True)
    heading = forms.CharField(label='PRESS RELEASE HEADING', max_length=500)
    description = forms.CharField(label='PRESS RELEASE DESCRIPTION', widget=forms.Textarea)

    class Meta:
        model = PressRelease
        # fields = ('company_name', 'email', 'image', 'heading', 'description')


class W4UForm(forms.Form):
    company_name = forms.CharField(label='COMPANY NAME', max_length=100, required=True)
    email = forms.EmailField(label='EMAIL ADDRESS', widget=forms.TextInput(attrs={'id': 'email'}), max_length=100,
                             validators=[validators.EmailValidator],
                             required=True)
    image = forms.ImageField(label='PRESS RELEASE IMAGE', required=True)  # widget=forms.ImageField,
    heading = forms.CharField(label='PRESS RELEASE HEADING', max_length=500)
    description = forms.CharField(label='PRESS RELEASE DESCRIPTION', widget=forms.Textarea)

    class Meta:
        model = WriteForUs
        # fields = ('company_name', 'email', 'image', 'heading', 'description')

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from .location import city
from .models import *
from django.utils import timezone
import bs4
from .forms import *


class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Post.objects.order_by('post_date')[:10]


def detail_page(request, pk, **kwargs):
    try:
        post = Post.objects.get(pk=pk)
        seen = post.seen
        seen += 1
        Post.objects.filter(pk=pk).update(seen=seen)
        head_line = ''
        soup = bs4.BeautifulSoup(post.post_content, features='lxml').h5
        if soup is not None:
            head_line = soup.get_text()
        context = {'post': post, 'head_line': head_line}
        return render(request, 'blog/article.html', context)
    except Exception as e:
        return HttpResponse(f"{e}")


def home_page(request):
    news_list = Post.objects.filter(category=1, schedule_time__lt=timezone.now(), post_status='published')[:3]
    # _city = city(request)
    lifestyle_list = []
    # if Post.objects.filter(city=_city, category=2).count() > 0:
    #     lifestyle_list = Post.objects.filter(category=2, city=_city, schedule_time__lt=timezone.now(),
    #                                          post_status='published')[:3]
    # else:
    lifestyle_list = Post.objects.filter(category=2, schedule_time__lt=timezone.now(), post_status='published')[:3]

    external_resources = NewsSource.objects.order_by('-created_at')[:3]
    context = {'news_list': news_list, 'lifestyle': lifestyle_list, 'news_source_list': external_resources}
    return render(request, 'blog/home.html', context)


def about_us_page(request):
    return render(request, 'blog/about_us.html')


def about_us_page_two(request):
    return render(request, 'blog/about_us_2.html')


def about_us_page_three(request):
    return render(request, 'blog/about_us_3.html')


def about_us_page_four(request):
    return render(request, 'blog/about_us_4.html')


def write_for_us_page(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        w4u = W4UForm(request.POST, request.FILES)
        # check whether it's valid:
        if w4u.is_valid():
            w4u.save()
            return HttpResponseRedirect('/thanks/')
        else:
            print(w4u.errors)
    else:
        form = W4UForm()
        return render(request, 'blog/temp.html', {'form': form})


def send_us_your_pr_page(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        press = PRForm(request.POST, request.FILES)
        # check whether it's valid:
        if press.is_valid():
            press.save()
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PRForm()
        return render(request, 'blog/send_us_your_pr.html', {'form': form})


def advertise_page(request):
    return render(request, 'blog/advertise.html')


def contact_us(request):
    return render(request, 'blog/contact-us.html')


def article_page(request, menu_id):
    article = Menu.objects.filter(menu=menu_id)
    context = {'article': article}
    return render(request, 'blog/menu_page.html', context=context)

blog/templates/blog/_detail.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %} Home {% endblock title %}
{% block content %}
<div class="news-item">
    <div class="row">
        <div class="col-12 col-md-6">
            <figure class="article-image">
                <img src="{% static 'images/article-image.jpg' %}" class="img-fluid w-100" alt="">
            </figure>
        </div>
        <div class="col-12 col-md-6">
            <div class="coontent-wrapper">
                <div class="sub-heading">
                    <h3>The UK detail.html its Covid-19 vaccination program. </h3>
                    <p>90-year-old Margaret Keenan was the first person to receive the Pfizer/BioNTech
                        jab; William Shakespeare, 81, was the second (seriously).90-year-old Margaret
                        Keenan was the first person to receive the Pfizer/BioNTech jab; William
                        Shakespeare, 81, was the second (seriously).90-year-old Margaret Keenan was th
                    </p>
                    <div class="bottom-widget">
                        <ul>
                            <li>
                                <span class="icon"><img src="{% static 'images/eye.svg' %}" alt=""></span>
                                <span class="value">100</span>
                            </li>
                            <li>
                                <span class="icon"><img src="{% static 'images/chat.svg' %}" alt=""></span>
                                <span class="value">32</span>
                            </li>
                            <li>
                                <span class="icon"><img src="{% static 'images/share.svg' %}" alt=""></span>
                                <span class="value">12</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/about_us.html
{% extends 'blog/layout/base.html' %}
{% load static %}
{% block content %}
<section class="about-header">
      <section class="about-title">
          <div>
              <img src="{% static 'icons/share.svg' %}" alt="share">
          </div>
          <hr>
          <h2>About Us</h2>
      </section>
      <section class="about-header-nav">
          <div>
              <p class="active-nav"><a class="link" href="{% url 'blog:about-us'%}">Our mission </a></p>
              <p><a class="link" href="{% url 'blog:what-drives-us'%}">What drives our news rooms</a></p>
          </div>
          <hr>
          <div>
              <p><a class="link" href="{% url 'blog:our-advertising-partners'%}">Our advertising partners</a></p>
              <p ><a class="link" href="{% url 'blog:make-money-with-us'%}">How we make money</a></p>
          </div>
      </section>
  </section>
<section class="about-mission">
    <h2>Our Mission</h2>
    <hr>
    <div class="mission-detail">
        <ul>
            <li>
                What we do is pretty simple; we explain the biggest stories to you in a way that you can
                actually relate to and therefore properly understand.
            </li>
            <li>
                We strip past the noise, fluff, polarization and BS to try show you that understanding
                what’s going on in the world isn’t as difficult as it may appear.
            </li>
        </ul>
        <span>
            If you feel as if we haven’t lived up to this, let us know here.
        </span>
    </div>
</section>
{% endblock content %}
{% block footer %}
<section class="banner article-banner w-1130">
    <div class="subscription">
        <div class="news-letter">
            <h4>SUBSCRIBE TO THE TMS NEWSLETTER</h4>
            <div class="signup-form">
                {% comment %} <img src="{% static 'icons/email_dark.svg' %}" alt="email"> {% endcomment %}
                <svg width="20" height="15" viewBox="0 0 20 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path
                            d="M20 12.4994C20 12.9379 19.8767 13.3443 19.6791 13.702L13.3643 6.63658L19.6106 1.17158C19.8536 1.55718 20 2.01014 20 2.49962V12.4994ZM10 7.91945L18.6916 0.314509C18.335 0.119253 17.9333 -0.000488281 17.5001 -0.000488281H2.49998C2.06619 -0.000488281 1.66443 0.119253 1.3092 0.314509L10 7.91945ZM12.4232 7.45936L10.4113 9.22082C10.2936 9.32333 10.1471 9.37452 10 9.37452C9.85287 9.37452 9.70633 9.32333 9.58865 9.22082L7.57633 7.45928L1.18163 14.615C1.56493 14.8554 2.01413 14.9995 2.49994 14.9995H17.5001C17.9858 14.9995 18.4352 14.8554 18.8184 14.615L12.4232 7.45936ZM0.389439 1.17154C0.146493 1.55714 0 2.0101 0 2.49962V12.4995C0 12.9379 0.122751 13.3444 0.321056 13.702L6.63513 6.63539L0.389439 1.17154Z"
                            fill="white" />
                    </svg>
                <input type="text" placeholder="Email">
                <button type="submit">Sign up</button>
            </div>
            <p>By providing your email, you agree to our Privacy Policy</p>
        </div>
        <div class="share">
            <h2>Share this page using the link down below</h2>
            <button class="copy-btn">
                <img src="{% static 'icons/copy-link.svg' %}" alt="copy link">
                <span>Copy link</span>
            </button>
        </div>
    </div>
</section>
<section class="social">
      {% comment %} <img src="{% static 'icons/twitter_dark.svg' %}" alt="twitter"> {% endcomment %}
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
            d="M22 5.92375C21.2563 6.25 20.4637 6.46625 19.6375 6.57125C20.4875 6.06375 21.1363 5.26625 21.4412 4.305C20.6488 4.7775 19.7738 5.11125 18.8412 5.2975C18.0887 4.49625 17.0162 4 15.8462 4C13.5763 4 11.7487 5.8425 11.7487 8.10125C11.7487 8.42625 11.7762 8.73875 11.8438 9.03625C8.435 8.87 5.41875 7.23625 3.3925 4.7475C3.03875 5.36125 2.83125 6.06375 2.83125 6.82C2.83125 8.24 3.5625 9.49875 4.6525 10.2275C3.99375 10.215 3.3475 10.0238 2.8 9.7225C2.8 9.735 2.8 9.75125 2.8 9.7675C2.8 11.76 4.22125 13.415 6.085 13.7962C5.75125 13.8875 5.3875 13.9312 5.01 13.9312C4.7475 13.9312 4.4825 13.9163 4.23375 13.8612C4.765 15.485 6.2725 16.6788 8.065 16.7175C6.67 17.8088 4.89875 18.4662 2.98125 18.4662C2.645 18.4662 2.3225 18.4513 2 18.41C3.81625 19.5813 5.96875 20.25 8.29 20.25C15.835 20.25 19.96 14 19.96 8.5825C19.96 8.40125 19.9538 8.22625 19.945 8.0525C20.7588 7.475 21.4425 6.75375 22 5.92375Z"
            fill="black" />
    </svg>

    {% comment %} <img src="{% static 'icons/linkedin_dark.svg' %}" alt="linked in"> {% endcomment %}
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
            d="M20.5576 2H3.44241C2.64575 2 2 2.64575 2 3.44241V20.5576C2 21.3542 2.64575 22 3.44241 22H20.5576C21.3542 22 22 21.3542 22 20.5576V3.44241C22 2.64575 21.3542 2 20.5576 2V2ZM9.09412 17.1172H6.65866V9.79007H9.09412V17.1172ZM7.87646 8.78955H7.8606C7.04333 8.78955 6.51477 8.22696 6.51477 7.52383C6.51477 6.80484 7.05951 6.25781 7.89264 6.25781C8.72577 6.25781 9.23846 6.80484 9.25433 7.52383C9.25433 8.22696 8.72577 8.78955 7.87646 8.78955ZM17.8759 17.1172H15.4407V13.1974C15.4407 12.2122 15.0881 11.5404 14.2069 11.5404C13.5341 11.5404 13.1334 11.9936 12.9573 12.4311C12.8929 12.5876 12.8772 12.8064 12.8772 13.0254V17.1172H10.4419C10.4419 17.1172 10.4738 10.4775 10.4419 9.79007H12.8772V10.8275C13.2009 10.3282 13.7799 9.6181 15.0721 9.6181C16.6744 9.6181 17.8759 10.6653 17.8759 12.9158V17.1172Z"
            fill="black" />
    </svg>
    {% comment %} <img src="{% static 'icons/facebook_dark.svg' %}" alt="Facebook"> {% endcomment %}
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
            d="M20.896 2H3.10303C2.49377 2.00037 1.99988 2.49451 2 3.104V20.897C2.00037 21.5062 2.49451 22.0001 3.104 22H12.6836V14.2656H10.0859V11.2383H12.6836V9.01038C12.6836 6.42676 14.2609 5.02051 16.5656 5.02051C17.6694 5.02051 18.618 5.10278 18.8945 5.13953V7.83984H17.3053C16.0514 7.83984 15.8086 8.43567 15.8086 9.31018V11.2383H18.8066L18.416 14.2656H15.8086V22H20.896C21.5056 22.0001 21.9999 21.5061 22 20.8965C22 20.8964 22 20.8962 22 20.896V3.10303C21.9998 2.49377 21.5055 1.99988 20.896 2Z"
            fill="black" />
    </svg>


    {% comment %} <img src="{% static 'icons/bookmark_dark.svg' %}" alt="bookmark"> {% endcomment %}
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
            d="M19.6625 2.66111C19.4906 2.41419 19.2591 2.23363 18.9685 2.11908C18.7834 2.03986 18.5895 2.00019 18.3867 2.00019V2H4.5333C4.33064 2 4.13688 2.03968 3.95178 2.1189C3.66102 2.23335 3.42961 2.41415 3.25779 2.66092C3.08602 2.9077 3 3.18077 3 3.48047V20.5195C3 20.8193 3.08602 21.0923 3.25779 21.3393C3.42961 21.586 3.66102 21.7668 3.95178 21.8812C4.1367 21.9604 4.33064 22 4.5333 22C4.94763 22 5.31316 21.8545 5.6305 21.564L11.4601 15.9589L17.2896 21.5641C17.5981 21.8456 17.9638 21.9867 18.3867 21.9867C18.6071 21.9867 18.801 21.9517 18.9684 21.8811C19.259 21.7667 19.4905 21.586 19.6624 21.3389C19.8342 21.0923 19.92 20.8192 19.92 20.5195V3.48065C19.9201 3.18096 19.834 2.90788 19.6625 2.66111ZM18.2281 20.1095L12.6366 14.7427L11.4601 13.6193L10.2836 14.7427L4.69215 20.1095V3.6922H18.2281V20.1095Z"
            fill="black" />
    </svg>

    {% comment %} <img src="{% static 'icons/more_dark.svg' %}" alt="more"> {% endcomment %}
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
            d="M19.1891 9C17.6368 8.99982 16.3783 10.2584 16.3783 11.8109C16.3783 13.3632 17.6368 14.6217 19.1891 14.6217C20.7416 14.6217 22 13.3632 22 11.8109C21.9982 10.2591 20.7409 9.00176 19.1891 9ZM19.1891 13.5011C18.2558 13.5011 17.4989 12.7442 17.4989 11.8109C17.4989 10.8775 18.2558 10.1208 19.1891 10.1208C20.1225 10.1208 20.8792 10.8773 20.8792 11.8109C20.8782 12.7439 20.122 13.4996 19.1891 13.5011Z"
            fill="black" />
        <path
            d="M12.0002 9C10.4477 9 9.18909 10.2584 9.18909 11.8109C9.18909 13.3632 10.4477 14.6217 12.0002 14.6217C13.5525 14.6217 14.8109 13.3632 14.8109 11.8109C14.8109 10.2584 13.5525 9 12.0002 9ZM12.0002 13.5011C11.0665 13.5011 10.3097 12.7442 10.3097 11.8109C10.3097 10.8773 11.0665 10.1208 12.0002 10.1208C12.9335 10.1208 13.6901 10.8773 13.6901 11.8109C13.6901 12.7442 12.9335 13.5011 12.0002 13.5011Z"
            fill="black" />
        <path
            d="M4.81092 9C3.25843 9 2 10.2584 2 11.8109C2 13.3632 3.25843 14.6217 4.81092 14.6217C6.36324 14.6217 7.62166 13.3632 7.62166 11.8109C7.61991 10.2591 6.36253 9.00176 4.81092 9ZM4.81092 13.5011C3.87746 13.5011 3.12079 12.7442 3.12079 11.8109C3.12079 10.8773 3.87746 10.1208 4.81092 10.1208C5.74438 10.1208 6.50088 10.8773 6.50088 11.8109C6.50088 12.7442 5.74421 13.5011 4.81092 13.5011Z"
            fill="black" />
    </svg>

</section>
<section class="copy-right">
    The Millennial Source Ltd. 2021
</section>

{% endblock footer %}

blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %} Home {% endblock title %}
{% block content %}
<div class="news-item">
    <div class="row">
        <div class="col-12 col-md-6">
            <figure class="article-image">
                <img src="{% static 'images/article-image.jpg' %}" class="img-fluid w-100" alt="">
            </figure>
        </div>
        <div class="col-12 col-md-6">
            <div class="coontent-wrapper">
                <div class="sub-heading">
                    <h3>The UK began its Covid-19 vaccination program. </h3>
                    <p>90-year-old Margaret Keenan was the first person to receive the Pfizer/BioNTech
                        jab; William Shakespeare, 81, was the second (seriously).90-year-old Margaret
                        Keenan was the first person to receive the Pfizer/BioNTech jab; William
                        Shakespeare, 81, was the second (seriously).90-year-old Margaret Keenan was th
                    </p>
                    <div class="bottom-widget">
                        <ul>
                            <li>
                                <span class="icon"><img src="{% static 'images/eye.svg' %}" alt=""></span>
                                <span class="value">100</span>
                            </li>
                            <li>
                                <span class="icon"><img src="{% static 'images/chat.svg' %}" alt=""></span>
                                <span class="value">32</span>
                            </li>
                            <li>
                                <span class="icon"><img src="{% static 'images/share.svg' %}" alt=""></span>
                                <span class="value">12</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/pressform.html
<form action="" method="POST">{% csrf_token %}
    {{ form.content }}
</form>

blog/templates/blog/temp.html
{% extends 'blog/layout/base.html' %}
{% load static%}
<!-- main start -->
<!-- {% load static %} -->
{% block content %}
<div class="wfu-header">
    <section class="about-title">
        <div>
            <img src="{% static 'icons/share.svg' %} " alt="share">
        </div>
        <hr>
        <h2>Send us your writing</h2>
    </section>
    <section class="wfu-form">

        <form enctype="multipart/form-data" action="{% url 'blog:temp' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>

  </section>
            </div>
{% endblock %}

{% block footer %}
<section class="social">
    <img src="{% static 'icons/twitter_dark.svg' %}" alt="twitter">
    <img src="{% static 'icons/linkedin_dark.svg' %}" alt="linked in">
    <img src="{% static 'icons/facebook_dark.svg' %}" alt="Facebook">
    <img src="{% static 'icons/bookmark_dark.svg' %}" alt="bookmark">
    <img src="{% static 'icons/more_dark.svg' %}" alt="more">
</section>
<section class="copy-right">
    The Millennial Source Ltd. 2021
</section>
{% endblock %}