blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    #  path('', views.IndexView.as_view()),

    path('detail/<int:pk>/', views.detail_page, name='detail'),
    path('', views.home_page,name='home'),
    path('about-us/', views.about_us_page, name='about-us'),
    path('what-drives-us/', views.about_us_page_two, name='what-drives-us'),
    path('our-advertising-partners/', views.about_us_page_three, name='our-advertising-partners'),
    path('make-money-with-us/', views.about_us_page_four, name='make-money-with-us'),
    path('write-for-us/', views.write_for_us_page, name='write-for-us'),
    path('send-us-your-pr/', views.send_us_your_pr_page, name='send-us-your-pr'),
    path('advertise/', views.advertise_page, name='advertise'),
    path('temp/', views.write_for_us_page, name='temp'),
    path('contact-us',view=views.contact_us, name='contact-us'),
    path('article-page/<int:menu_id>/',view=views.article_page, name='article-page')
]

themisource/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include('blog.urls')),
  path('summernote/', include('django_summernote.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import datetime
from django.contrib.auth.models import User
from django.core import validators
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy as _


def post_upload_to(instance, filename):
    return 'blog/post/{filename}'.format(filename=filename)


def logo_upload_to(instance, filename):
    return 'blog/post/{filename}'.format(filename=filename)


def ns_upload_to(instance, filename):
    return 'blog/source/{filename}'.format(filename=filename)


def wfu_upload_to(instance, filename):
    return 'blog/write4us/{filename}'.format(filename=filename)


def press_upload_to(instance, filename):
    return 'blog/press/{filename}'.format(filename=filename)


class Category(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Post(models.Model):

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    editor = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='editor')
    post_date = models.DateTimeField(auto_now_add=True)
    schedule_time = models.DateTimeField(default=timezone.now)
    post_content = models.TextField()
    post_title = models.CharField(max_length=1000, null=False)
    post_status = models.CharField(max_length=20,  choices=options, default='published')
    post_modified = models.DateTimeField(auto_now=True, null=True)
    category = models.ForeignKey(Category, related_name='category_id', on_delete=models.CASCADE)
    city = models.CharField(max_length=100, null=True, blank=True)
    tags = models.CharField(max_length=500, null=True, blank=True)
    keywords = models.CharField(max_length=500, null=True, blank=True)
    slug = models.SlugField(max_length=200)
    meta_title = models.CharField(max_length=500, null=True, blank=True)
    meta_description = models.TextField(null=True, blank=True)
    feature_image_url = models.ImageField(_("Image"), upload_to=post_upload_to, default='blog/post/default.jpg')
    seen = models.BigIntegerField(default=0)
    objects = models.Manager()  # default manager

    class Meta:
        ordering = ('-post_date',)

    def __str__(self):
        return self.post_title

    def published(self):
        return self.schedule_time < timezone.now() and self.post_status == 'published'


class Comments(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user_name = models.CharField(max_length=250)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user_name


class PressRelease(models.Model):
    company_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, validators=[validators.EmailValidator])
    image = models.ImageField(_("Image"), upload_to=press_upload_to, default='blog/press/default.jpg')
    heading = models.CharField(max_length=500)
    description = models.TextField()
    created_at = models.DateTimeField(default=timezone.now, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.heading


class WriteForUs(models.Model):
    company_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, validators=[validators.EmailValidator])
    image = models.ImageField(_("Image"), upload_to=wfu_upload_to, default='blog/write4us/default.jpg')
    heading = models.CharField(max_length=500)
    description = models.TextField()
    created_at = models.DateTimeField(default=timezone.now, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.heading


class NewsSource(models.Model):
    title = models.CharField(max_length=500)
    description = models.TextField()
    url = models.URLField()
    image = models.ImageField(_("Image"), upload_to=ns_upload_to, default='blog/source/default.png')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.title


class Menu(models.Model):
    title = models.CharField(max_length=100, unique=True)
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE, related_name='children')
    url = models.URLField(blank=True, null=True)
    is_static = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name='menus')
    title = models.CharField(max_length=255)
    body = models.TextField()
    slug = models.SlugField(null=False, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

blog/forms.py
from django import forms
from django.core import validators
from .models import *


class PRForm(forms.Form):
    company_name = forms.CharField(label='COMPANY NAME', max_length=100, required=True)
    email = forms.EmailField(label='EMAIL ADDRESS', max_length=100, validators=[validators.EmailValidator],
                             required=True)
    image = forms.ImageField(label='PRESS RELEASE IMAGE', widget=forms.ImageField, required=True)
    heading = forms.CharField(label='PRESS RELEASE HEADING', max_length=500)
    description = forms.CharField(label='PRESS RELEASE DESCRIPTION', widget=forms.Textarea)

    class Meta:
        model = PressRelease
        # fields = ('company_name', 'email', 'image', 'heading', 'description')


class W4UForm(forms.Form):
    company_name = forms.CharField(label='COMPANY NAME', max_length=100, required=True)
    email = forms.EmailField(label='EMAIL ADDRESS', widget=forms.TextInput(attrs={'id': 'email'}), max_length=100,
                             validators=[validators.EmailValidator],
                             required=True)
    image = forms.ImageField(label='PRESS RELEASE IMAGE', required=True)  # widget=forms.ImageField,
    heading = forms.CharField(label='PRESS RELEASE HEADING', max_length=500)
    description = forms.CharField(label='PRESS RELEASE DESCRIPTION', widget=forms.Textarea)

    class Meta:
        model = WriteForUs
        # fields = ('company_name', 'email', 'image', 'heading', 'description')

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from .location import city
from .models import *
from django.utils import timezone
import bs4
from .forms import *


class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Post.objects.order_by('post_date')[:10]


def detail_page(request, pk, **kwargs):
    try:
        post = Post.objects.get(pk=pk)
        seen = post.seen
        seen += 1
        Post.objects.filter(pk=pk).update(seen=seen)
        head_line = ''
        soup = bs4.BeautifulSoup(post.post_content, features='lxml').h5
        if soup is not None:
            head_line = soup.get_text()
        context = {'post': post, 'head_line': head_line}
        return render(request, 'blog/article.html', context)
    except Exception as e:
        return HttpResponse(f"{e}")


def home_page(request):
    news_list = Post.objects.filter(category=1, schedule_time__lt=timezone.now(), post_status='published')[:3]
    # _city = city(request)
    lifestyle_list = []
    # if Post.objects.filter(city=_city, category=2).count() > 0:
    #     lifestyle_list = Post.objects.filter(category=2, city=_city, schedule_time__lt=timezone.now(),
    #                                          post_status='published')[:3]
    # else:
    lifestyle_list = Post.objects.filter(category=2, schedule_time__lt=timezone.now(), post_status='published')[:3]

    external_resources = NewsSource.objects.order_by('-created_at')[:3]
    context = {'news_list': news_list, 'lifestyle': lifestyle_list, 'news_source_list': external_resources}
    return render(request, 'blog/home.html', context)


def about_us_page(request):
    return render(request, 'blog/about_us.html')


def about_us_page_two(request):
    return render(request, 'blog/about_us_2.html')


def about_us_page_three(request):
    return render(request, 'blog/about_us_3.html')


def about_us_page_four(request):
    return render(request, 'blog/about_us_4.html')


def write_for_us_page(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        w4u = W4UForm(request.POST, request.FILES)
        # check whether it's valid:
        if w4u.is_valid():
            w4u.save()
            return HttpResponseRedirect('/thanks/')
        else:
            print(w4u.errors)
    else:
        form = W4UForm()
        return render(request, 'blog/temp.html', {'form': form})


def send_us_your_pr_page(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        press = PRForm(request.POST, request.FILES)
        # check whether it's valid:
        if press.is_valid():
            press.save()
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PRForm()
        return render(request, 'blog/send_us_your_pr.html', {'form': form})


def advertise_page(request):
    return render(request, 'blog/advertise.html')


def contact_us(request):
    return render(request, 'blog/contact-us.html')


def article_page(request, menu_id):
    article = Menu.objects.filter(menu=menu_id)
    context = {'article': article}
    return render(request, 'blog/menu_page.html', context=context)

blog/templates/blog/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="theme-light">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style_light.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_menu.css' %}">
    <title>Home </title>
</head>

<body>
    <!-- menu start  -->
    <div class="menu-wrapper" id="main-menu">
        <nav>
            <div class="menu-header">
                <img src="{% static 'icons/close.svg' %}" alt="close" class="close-icon" id="close-button">
                <div class="menu-search">
                    <div>
                        <img src="{% static 'icons/search.svg' %}" alt="search">
                        <input type="text" name="search" placeholder="Search">
                        <hr>
                    </div>
                </div>
            </div>
            <div class="menu-category">
                <div class="menu-discover">
                    <h1 class="menu-title">Discover</h1>
                    <div class="menu-body">
                        <a href="{% url 'blog:about-us' %}">About Us</a>
                        <a href="{% url 'blog:contact-us' %}">Careers</a>
                        <a href="{% url 'blog:contact-us' %}">Contact</a>
                        <a href="{% url 'blog:advertise' %}">Advertise</a>
                        <a href="#">Archives</a>
                        <a href="{% url 'blog:write-for-us' %}">Write for us</a>
                        <a href="{% url 'blog:send-us-your-pr' %}">Send us your press release</a>
                        <a href="#">Privacy policy</a>
                        <a href="#">Terms of service</a>
                    </div>
                </div>
                <div class="menu-hot-topics">
                    <h1 class="menu-title">Reads On</h1>
                    <div class="menu-body">
                        <a href="#">Crypto</a>
                        <a href="#">Startups</a>
                        <a href="#">Economy</a>
                        <a href="#">Electric vehicles</a>
                        <a href="#">Superpower relations</a>
                        <a href="#">Tech giants</a>
                        <a href="#">Climate change</a>
                        <a href="#">Future of work</a>
                        <a href="#">Cultural movements </a>
                        <a href="#">Space race</a>
                        <a href="#">Banking giants</a>
                    </div>
                </div>
                <div class="menu-lifestyle">
                    <h1 class="menu-title">Life Style</h1>
                    <div class="menu-body">
                        <a href="#">Health</a>
                        <a href="#">Travel</a>
                        <a href="#">Entertainment</a>
                        <a href="#">Technology</a>
                    </div>
                </div>
                {% comment %} <div class="menu-more">
                    <h1 class="menu-title">More</h1>
                    <div class="menu-body">
                        <a href="#">Future of work</a>
                        <a href="#">Cultural movements </a>
                        <a href="#">Space race</a>
                        <a href="#">Banking giants</a>
                    </div>
                </div> {% endcomment %}
                <div class="menu-social">
                    <h1 class="menu-title">Follow us</h1>
                    <div>
                        <img src="{% static 'icons/twitter_m.svg' %}" alt="twitter">
                        <img src="{% static 'icons/linkedin_m.svg' %}" alt="linkedin">
                        <img src="{% static 'icons/facebook_m.svg' %}" alt="facebook">
                        <img src="{% static 'icons/insta_menu.svg' %}" alt="insta">
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <!-- menu end  -->
    {% comment %} {% for m in menus %}
        {{m.title}}
    {% endfor %} {% endcomment %}
    <div class="container">
        <header>
            <div class="inner">
                <div class="left-content">
                    <div class="menu-button">
                        {% comment %} <img src="{% static 'icons/Menu_dark.svg' %}" alt="menu" id="show-button">
                        {% endcomment %}
                        <svg width="29" height="38" viewBox="0 0 29 38" fill="none" xmlns="http://www.w3.org/2000/svg" id="show-button">
                            <line y1="13.25" x2="20" y2="13.25" stroke="black" stroke-width="1.5" />
                            <line y1="18.25" x2="20" y2="18.25" stroke="black" stroke-width="1.5" />
                            <line y1="23.25" x2="20" y2="23.25" stroke="black" stroke-width="1.5" />
                        </svg>
                    </div>

                    <div class="view">
                        {% comment %} <img src="{% static 'icons/top_views.svg' %}" alt="views" class="icon-view">
                        {% endcomment %}
                        <svg width="78" height="44" viewBox="0 0 78 44" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M76.8699 21.6458C76.7015 21.4434 59.6971 1 38.9977 1C18.2982 1 1.29393 21.4434 1.12546 21.6458C1.0443 21.746 1 21.871 1 22C1 22.129 1.0443 22.2541 1.12546 22.3542C1.29393 22.5566 18.2982 43 38.9977 43C59.6971 43 76.7015 22.5679 76.8699 22.3655C76.954 22.2644 77 22.1371 77 22.0056C77 21.8741 76.954 21.7468 76.8699 21.6458Z"
                                fill="#EEEFEF" stroke="#38B6FF" />
                        </svg>
                        <div class="overlay-text">25K</div>
                    </div>

                </div>
                <div class="center-content">
                    <a href="{% url 'blog:home' %}">
                        {% comment %} <h1 class="title">TMS</h1> {% endcomment %}
                        <img src="{% static 'images/logo_dark.png' %}" alt="logo" height="36" id="site-logo">
                        {% comment %} <img src="{% static 'images/logo_light.png' %}" alt="logo" height="36"> {% endcomment %}
                    </a>
                </div>

                <div class="right-content">

                    <div class="theme-change-button">
                        {% comment %} <img src="{% static 'icons/light.svg' %}" alt=""> {% endcomment %}
                        <button id="switch" onclick="toggleTheme()">Switch</button>
                    </div>
                    <div class="current-date">
                        {% now " l, F d, Y" %}
                        <hr>
                    </div>
                </div>
            </div>
        </header>
        {% block content %}

        {% endblock %}
        <footer>
            {% block footer %}

            {% endblock footer %}
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <script src="{% static 'js/GreetingPlugin.js' %} "></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>